name: CI-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  all-test:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Set up Docker Compose
        run: |
          docker --version
          docker compose --version
      
      - name: Start Application
        run: | 
          docker compose up -d
   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init

      - name: Robot
        env:
            WORK_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          robot -d test-results e2e-tests/

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 Performance tests 
        uses: grafana/run-k6-action@v1
        with:
          path: script.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: robot-test-results
          retention-days: 3

  smoke-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Set up Docker Compose
        run: |
          docker --version
          docker compose --version
      
      - name: Start Application
        run: | 
          docker compose up -d
   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init

      - name: Robot
        env:
            WORK_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          robot --include smoke -d results/smoke e2e-tests/

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 Performance tests 
        uses: grafana/run-k6-action@v1
        with:
          path: script.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: robot-test-results
          retention-days: 3