name: CI-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Set up Docker Compose
        run: |
          docker --version
          docker compose --version
      
      - name: Start Application
        run: | 
          docker compose up -d
   
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init


      - name: Robot
        env:
            WORK_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          robot -d tests
        continue-on-error: true

      - name: Run Robot Framework tests
        env:
          WORK_TOKEN: ${{ secrets.GIT_TOKEN }}
          TZ: Asia/Ho_Chi_Minh
        run: |
          if ! robot --outputdir results --exclude skip tests/; then
              echo "Robot Framework tests failed. Rerunning failed tests..."
              if [ -f results/output.xml ]; then
                  robot --rerunfailed results/output.xml --outputdir results_rerun tests/ || true
                  if [ -f results_rerun/output.xml ]; then
                      rebot --output results/output.xml --log results/log.html --report results/report.html --merge results/output.xml results_rerun/output.xml
                  else
                      echo "No output.xml file found from rerun. Skipping merge."
                  fi
              else
                  echo "No output.xml file found. Cannot rerun failed tests."
              fi
          fi

          echo "Script execution completed"
        continue-on-error: true

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run K6 Performance tests 
        uses: grafana/run-k6-action@v1
        with:
          path: script.js

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: robot-test-results
          retention-days: 3